### ISSUE TITLE
get_remote breaks if remote is local

### ISSUE THREAD

**Issue by bengranett** [didamarkovic/metafil#3]
When the remote is actually a local directory, then the URLs look like this:
```
bla@bla:~/bla$ git remote -v
origin  /home/bla/repo.git/ (fetch)
origin  /home/bla/repo.git/ (push)
```

and `metafil.GitEnv` crashes because `ssh_url` gets set to `None`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bla/.virtualenvs/bla/local/lib/python2.7/site-packages/metafil.py", line 304, in __init__
    self.url = str(self.get_remote()).split('@')[-1]
  File "/home/bla/.virtualenvs/bla/local/lib/python2.7/site-packages/metafil.py", line 381, in get_remote
    ssh_url = cmd_out.strip().split('git@')[1].split(' ')[0]
IndexError: list index out of range
```

**Comment by didamarkovic** [comment]
I would like to start using `GitPython`, which will hopefully fix this.

**Comment by didamarkovic** [comment]
Check out the new branch, gitpy. I'll submit a merge request for you to have a look at, @bengranett.

**Comment by didamarkovic** [comment]
Does it work if you use what I did in #5?

**Comment by bengranett** [comment]
yes, it works from a repo that is cloned from a local directory.
